# Generated by Django 4.2.7 on 2024-04-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.IntegerField(unique=True)),
                ('vehicle_registration_plate', models.CharField(blank=True, max_length=100, null=True)),
                ('vin', models.CharField(max_length=100)),
                ('stock_number', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('trim', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('body_style', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(max_length=100)),
                ('drivetrain', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.JSONField(default=list)),
                ('mileage_value', models.IntegerField()),
                ('mileage_unit', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state_of_vehicle', models.CharField(max_length=100)),
                ('exterior_color', models.CharField(max_length=100)),
                ('interior_color', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('dealer_id', models.IntegerField(blank=True, null=True)),
                ('dealer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dealer_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('fb_page_id', models.BigIntegerField(blank=True, null=True)),
                ('dealer_communication_channel', models.CharField(blank=True, max_length=100, null=True)),
                ('dealer_privacy_policy_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
